### ISSUE TITLE
Bug: exclude is not correctly applied

### ISSUE THREAD

**Issue by LumaKernel** [LumaKernel/cargo-glue#1]
It seems it's because of version mismatch for `krates` and `cargo-metadata`.

```rs
use krates::{cm, PkgSpec};
fn main() {
    let metadata = cm::MetadataCommand::new()
        .manifest_path("Cargo.toml")
        .current_dir("/<proj>/demo")
        .exec()
        .unwrap();

    dbg!(&metadata);
    let pid = metadata
        .clone()
        .resolve
        .unwrap()
        .nodes
        .first()
        .cloned()
        .unwrap()
        .deps
        .first()
        .cloned()
        .unwrap();
    dbg!(&pid);
    let pk = &metadata[&pid.pkg];
    //dbg!(&pk);

    let s = "https://github.com/rust-lang/crates.io-index#proconio:0.4.5";
    let ps = s.parse::<PkgSpec>().unwrap();
    //ps.matches();
    let r = ps.matches(pk);
    dbg!(&r);
}
```

```toml
[dependencies]
krates = "0.17.2"
```

```toml
# demo/Cargo.toml
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
demo = { problem = "https://atcoder.jp/contests/..." }
[[bin]]
name = "demo"
path = "src/bin/a.rs"
[dependencies]
proconio = "=0.4.5"
[dev-dependencies]
```

In krates v0.8, it's checking id which is just string. 

https://github.com/EmbarkStudios/krates/blob/85519034/src/pkgspec.rs#L30

```rs
Some(ref u) => {
                // Get the url from the identifier to avoid pointless
                // allocations.
                if let Some(mut url) = krate.id.repr.splitn(3, ' ').nth(2) {
                    // Strip off the the enclosing parens
                    url = &url[1..url.len() - 1];

                    // Strip off the leading <source>+
                    if let Some(ind) = url.find('+') {
                        url = &url[ind + 1..];
                    }
```

I believe id format is changed.
